name: 'HaxExtend'

on:
  push:
  schedule:
    # run every 3 days on UTC 0/1/2am (8/9/10am CN time)
     - cron: '0 1 */2 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  extend_in_gh:
    runs-on: ubuntu-latest
    steps:
      -
        name: install wgcf
        run: |
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ focal main' | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt update
          sudo apt install cloudflare-warp -y
          warp-cli  --accept-tos register 
          warp-cli  --accept-tos connect        
      -
        name: "run"
        run: |
          docker images
          docker run -e USERNAME=${{ secrets.USERNAME }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e TWOCAPTCHA_TOKEN=${{ secrets.TWOCAPTCHA_TOKEN }} \
          -e HOST=hax.co.id \
          ghcr.io/lyj0309/hax_extend:latest
          

